import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { resolve } from 'node:path';

const project = fileURLToPath(new URL('../', import.meta.url));
const fail = (message) => { throw new Error(`Tape config: ${message}`); };
const nonempty = (value) => typeof value === 'string' && value.trim().length > 0;

export function compileCatalog(config) {
  if (!config || typeof config !== 'object') fail('expected an object.');
  let base;
  try { base = new URL(config.audioBaseUrl); } catch { fail('audioBaseUrl must be an absolute HTTP(S) URL.'); }
  if (!['http:', 'https:'].includes(base.protocol) || base.username || base.password || base.search || base.hash) fail('audioBaseUrl must be an HTTP(S) URL without credentials, a query, or a fragment.');
  if (!base.pathname.endsWith('/')) base.pathname += '/';
  if (!Array.isArray(config.tapes) || !config.tapes.length) fail('tapes must contain at least one tape.');
  const ids = new Set();
  const tracks = config.tapes.map((tape, index) => {
    const label = `tapes[${index}]`;
    if (!tape || !nonempty(tape.id) || !nonempty(tape.title) || typeof tape.artist !== 'string' || !nonempty(tape.file)) fail(`${label} requires id, title, artist (may be empty), and file.`);
    if (ids.has(tape.id)) fail(`duplicate id "${tape.id}".`);
    ids.add(tape.id);
    let segments;
    try { segments = tape.file.split('/').map(decodeURIComponent); } catch { fail(`${label}.file contains invalid percent encoding.`); }
    if (segments.some(segment => !segment || segment === '.' || segment === '..' || /[\\/\x00-\x1f]/.test(segment))) fail(`${label}.file must be a relative audio key, not a URL or parent path.`);
    const url = new URL(segments.map(encodeURIComponent).join('/'), base).href;
    if (tape.durationSeconds !== undefined && (!Number.isFinite(tape.durationSeconds) || tape.durationSeconds <= 0)) fail(`${label}.durationSeconds must be positive.`);
    if (tape.chapters !== undefined && !Array.isArray(tape.chapters)) fail(`${label}.chapters must be an array.`);
    let previousEnd = 0;
    const chapters = (tape.chapters ?? []).map((chapter, chapterIndex) => {
      if (!chapter || !nonempty(chapter.title) || !Number.isFinite(chapter.startSeconds) || !Number.isFinite(chapter.endSeconds) || chapter.startSeconds < previousEnd || chapter.endSeconds <= chapter.startSeconds) fail(`${label}.chapters[${chapterIndex}] requires a title and ordered, nonoverlapping startSeconds/endSeconds.`);
      if (chapterIndex === 0 && chapter.startSeconds !== 0) fail(`${label}'s first chapter must start at zero.`);
      if (tape.durationSeconds && chapter.endSeconds > tape.durationSeconds + .001) fail(`${label}'s chapter ends after the tape duration.`);
      previousEnd = chapter.endSeconds;
      return { id: chapter.id || `ch${String(chapterIndex + 1).padStart(3, '0')}`, title: chapter.title, startSeconds: chapter.startSeconds, endSeconds: chapter.endSeconds };
    });
    return { id: index + 1, key: tape.id, title: tape.title, artist: tape.artist, file: tape.file, url, ...(tape.durationSeconds ? { durationSeconds: tape.durationSeconds } : {}), ...(chapters.length ? { chapters } : {}) };
  });
  return { audioBaseUrl: base.href, tracks };
}

const escapeHtml = (value) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

export async function build({ configPath = resolve(project, 'config/tapes.json'), outputPath = resolve(project, 'dist') } = {}) {
  const catalog = compileCatalog(JSON.parse(await readFile(configPath, 'utf8')));
  const html = (await readFile(resolve(project, 'src/index.html'), 'utf8'))
    .replaceAll('__TAPE_COUNT__', String(catalog.tracks.length))
    .replaceAll('__FIRST_TAPE_URL__', escapeHtml(catalog.tracks[0].url));
  await mkdir(outputPath, { recursive: true });
  await writeFile(resolve(outputPath, 'index.html'), html);
  await writeFile(resolve(outputPath, 'tracks.js'), '// Generated by npm run build from config/tapes.json. Do not edit.\n'
    + `export const AUDIO_BASE = ${JSON.stringify(catalog.audioBaseUrl)};\n`
    + `export const tracks = ${JSON.stringify(catalog.tracks, null, 2)};\n`);
  for (const file of ['app.js', 'styles.css', 'favicon.svg']) await copyFile(resolve(project, 'src', file), resolve(outputPath, file));
  console.log(`Built ${catalog.tracks.length} tapes from ${configPath}`);
  return catalog;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try { await build(); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
